// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpoaxhvkocwcypeybnzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwb2F4aHZrb2N3Y3lwZXlibnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDg2MDIsImV4cCI6MjA1OTkyNDYwMn0.eujE3kLSupPZrZvyIFC0YoNFqR7rg5SzkMqi-5XsVlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);